/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module sar_logic(clk, rstn, en, comp, cal, valid, result, sample, ctlp, ctln, trim, trimb, clkc);
  wire [3:0] _000_;
  wire [3:0] _001_;
  wire _002_;
  wire _003_;
  wire [7:0] _004_;
  wire [7:0] _005_;
  wire [2:0] _006_;
  wire [4:0] _007_;
  wire [4:0] _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  input cal;
  wire [3:0] cal_count;
  wire [3:0] cal_itt;
  wire calibrate;
  input clk;
  output clkc;
  wire co_clk;
  input comp;
  output [7:0] ctln;
  output [7:0] ctlp;
  input en;
  wire en_co_clk;
  wire [7:0] mask;
  output [7:0] result;
  input rstn;
  output sample;
  wire [2:0] state;
  output [4:0] trim;
  wire [4:0] trim_mask;
  wire [4:0] trim_val;
  output [4:0] trimb;
  output valid;
  sky130_fd_sc_hd__clkinv_1 _384_ (
    .A(_167_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__clkinv_1 _385_ (
    .A(_050_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__clkinv_1 _386_ (
    .A(_051_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__clkinv_1 _387_ (
    .A(_165_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__clkinv_1 _388_ (
    .A(_057_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _389_ (
    .A(_161_),
    .SLEEP(_084_),
    .X(_074_)
  );
  sky130_fd_sc_hd__clkinv_1 _390_ (
    .A(_074_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _391_ (
    .A(_162_),
    .SLEEP(_085_),
    .X(_075_)
  );
  sky130_fd_sc_hd__clkinv_1 _392_ (
    .A(_075_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _393_ (
    .A(_163_),
    .SLEEP(_086_),
    .X(_076_)
  );
  sky130_fd_sc_hd__clkinv_1 _394_ (
    .A(_076_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__and4b_1 _395_ (
    .A_N(_056_),
    .B(_055_),
    .C(_053_),
    .D(_054_),
    .X(_092_)
  );
  sky130_fd_sc_hd__nand4b_1 _396_ (
    .A_N(_056_),
    .B(_055_),
    .C(_053_),
    .D(_054_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nand2_1 _397_ (
    .A(_053_),
    .B(_093_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nand2b_1 _398_ (
    .A_N(_166_),
    .B(_165_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nand3b_1 _399_ (
    .A_N(_166_),
    .B(_165_),
    .C(_167_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nor2_1 _400_ (
    .A(_092_),
    .B(_096_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nand2_1 _401_ (
    .A(_173_),
    .B(_053_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__a21oi_1 _402_ (
    .A1(_092_),
    .A2(_098_),
    .B1(_096_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__o21bai_1 _403_ (
    .A1(_167_),
    .A2(_077_),
    .B1_N(_095_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__a22o_1 _404_ (
    .A1(_094_),
    .A2(_099_),
    .B1(_100_),
    .B2(_053_),
    .X(_013_)
  );
  sky130_fd_sc_hd__xor2_1 _405_ (
    .A(_053_),
    .B(_054_),
    .X(_101_)
  );
  sky130_fd_sc_hd__o21ai_0 _406_ (
    .A1(_092_),
    .A2(_101_),
    .B1(_099_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nand2_1 _407_ (
    .A(_054_),
    .B(_100_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nand2_1 _408_ (
    .A(_102_),
    .B(_103_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__a21o_1 _409_ (
    .A1(_053_),
    .A2(_054_),
    .B1(_055_),
    .X(_104_)
  );
  sky130_fd_sc_hd__nand4_1 _410_ (
    .A(_053_),
    .B(_054_),
    .C(_056_),
    .D(_055_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__a32o_1 _411_ (
    .A1(_099_),
    .A2(_104_),
    .A3(_105_),
    .B1(_100_),
    .B2(_055_),
    .X(_015_)
  );
  sky130_fd_sc_hd__a31oi_1 _412_ (
    .A1(_053_),
    .A2(_054_),
    .A3(_055_),
    .B1(_087_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__o21a_1 _413_ (
    .A1(_100_),
    .A2(_106_),
    .B1(_056_),
    .X(_016_)
  );
  sky130_fd_sc_hd__mux2i_1 _414_ (
    .A0(_100_),
    .A1(_097_),
    .S(_049_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__xor2_1 _415_ (
    .A(_049_),
    .B(_050_),
    .X(_107_)
  );
  sky130_fd_sc_hd__xnor2_1 _416_ (
    .A(_060_),
    .B(_107_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__a22oi_1 _417_ (
    .A1(_088_),
    .A2(_100_),
    .B1(_108_),
    .B2(_097_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__or3b_1 _418_ (
    .A(_049_),
    .B(_050_),
    .C_N(_060_),
    .X(_109_)
  );
  sky130_fd_sc_hd__nand3b_1 _419_ (
    .A_N(_060_),
    .B(_050_),
    .C(_049_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__nand2_1 _420_ (
    .A(_109_),
    .B(_110_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__nand3_1 _421_ (
    .A(_051_),
    .B(_109_),
    .C(_110_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__nand2_1 _422_ (
    .A(_089_),
    .B(_111_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__a32oi_1 _423_ (
    .A1(_097_),
    .A2(_112_),
    .A3(_113_),
    .B1(_100_),
    .B2(_089_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__mux2i_1 _424_ (
    .A0(_109_),
    .A1(_110_),
    .S(_051_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__xor2_1 _425_ (
    .A(_052_),
    .B(_114_),
    .X(_115_)
  );
  sky130_fd_sc_hd__a22o_1 _426_ (
    .A1(_052_),
    .A2(_100_),
    .B1(_115_),
    .B2(_097_),
    .X(_012_)
  );
  sky130_fd_sc_hd__nand2b_1 _427_ (
    .A_N(_167_),
    .B(_165_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__nor3b_1 _428_ (
    .A(_166_),
    .B(_116_),
    .C_N(_077_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__a21oi_1 _429_ (
    .A1(_173_),
    .A2(_092_),
    .B1(_096_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__and3b_1 _430_ (
    .A_N(_167_),
    .B(_166_),
    .C(_165_),
    .X(_119_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _431_ (
    .A(_119_),
    .SLEEP(_079_),
    .X(_120_)
  );
  sky130_fd_sc_hd__a21oi_1 _432_ (
    .A1(_166_),
    .A2(_079_),
    .B1(_116_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__o22ai_1 _433_ (
    .A1(_078_),
    .A2(_117_),
    .B1(_118_),
    .B2(_121_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__nand3_1 _434_ (
    .A(_078_),
    .B(_096_),
    .C(_116_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__nand2_1 _435_ (
    .A(_122_),
    .B(_123_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _436_ (
    .A(_173_),
    .SLEEP(_178_),
    .X(_168_)
  );
  sky130_fd_sc_hd__clkinv_1 _437_ (
    .A(_168_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__or3_1 _438_ (
    .A(_167_),
    .B(_166_),
    .C(_165_),
    .X(_124_)
  );
  sky130_fd_sc_hd__nor3b_1 _439_ (
    .A(_167_),
    .B(_165_),
    .C_N(_166_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__nand2_1 _440_ (
    .A(_057_),
    .B(_125_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__nand2_1 _441_ (
    .A(_124_),
    .B(_126_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__and3_1 _442_ (
    .A(_178_),
    .B(_124_),
    .C(_126_),
    .X(_128_)
  );
  sky130_fd_sc_hd__nor2_1 _443_ (
    .A(_093_),
    .B(_096_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__a31o_1 _444_ (
    .A1(_173_),
    .A2(_052_),
    .A3(_129_),
    .B1(_128_),
    .X(_043_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _445_ (
    .A(_179_),
    .SLEEP(_174_),
    .X(_169_)
  );
  sky130_fd_sc_hd__clkinv_1 _446_ (
    .A(_169_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__a21oi_1 _447_ (
    .A1(_052_),
    .A2(_129_),
    .B1(_179_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__nor3_1 _448_ (
    .A(_127_),
    .B(_184_),
    .C(_130_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _449_ (
    .A(_180_),
    .SLEEP(_175_),
    .X(_170_)
  );
  sky130_fd_sc_hd__clkinv_1 _450_ (
    .A(_170_),
    .Y(_185_)
  );
  sky130_fd_sc_hd__a31oi_1 _451_ (
    .A1(_052_),
    .A2(_175_),
    .A3(_129_),
    .B1(_180_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nor2_1 _452_ (
    .A(_127_),
    .B(_131_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _453_ (
    .A(_181_),
    .SLEEP(_176_),
    .X(_171_)
  );
  sky130_fd_sc_hd__clkinv_1 _454_ (
    .A(_171_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__a21oi_1 _455_ (
    .A1(_052_),
    .A2(_129_),
    .B1(_181_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nor3_1 _456_ (
    .A(_127_),
    .B(_186_),
    .C(_132_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nor2_1 _457_ (
    .A(_182_),
    .B(_177_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__clkinv_1 _458_ (
    .A(_187_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__a21oi_1 _459_ (
    .A1(_052_),
    .A2(_129_),
    .B1(_182_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__o31ai_1 _460_ (
    .A1(_127_),
    .A2(_187_),
    .A3(_133_),
    .B1(_124_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__a21oi_1 _461_ (
    .A1(_057_),
    .A2(_125_),
    .B1(_129_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__a22o_1 _462_ (
    .A1(_174_),
    .A2(_129_),
    .B1(_134_),
    .B2(_173_),
    .X(_038_)
  );
  sky130_fd_sc_hd__a22o_1 _463_ (
    .A1(_175_),
    .A2(_129_),
    .B1(_134_),
    .B2(_174_),
    .X(_039_)
  );
  sky130_fd_sc_hd__a22o_1 _464_ (
    .A1(_176_),
    .A2(_129_),
    .B1(_134_),
    .B2(_175_),
    .X(_040_)
  );
  sky130_fd_sc_hd__a22o_1 _465_ (
    .A1(_177_),
    .A2(_129_),
    .B1(_134_),
    .B2(_176_),
    .X(_041_)
  );
  sky130_fd_sc_hd__o21ai_0 _466_ (
    .A1(_093_),
    .A2(_096_),
    .B1(_177_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__nand2_1 _467_ (
    .A(_126_),
    .B(_135_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nor3_1 _468_ (
    .A(_077_),
    .B(_166_),
    .C(_116_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _469_ (
    .A(_116_),
    .SLEEP(_136_),
    .X(_137_)
  );
  sky130_fd_sc_hd__a22o_1 _470_ (
    .A1(_080_),
    .A2(_119_),
    .B1(_137_),
    .B2(_079_),
    .X(_019_)
  );
  sky130_fd_sc_hd__a22o_1 _471_ (
    .A1(_081_),
    .A2(_119_),
    .B1(_137_),
    .B2(_080_),
    .X(_020_)
  );
  sky130_fd_sc_hd__a22o_1 _472_ (
    .A1(_082_),
    .A2(_119_),
    .B1(_137_),
    .B2(_081_),
    .X(_021_)
  );
  sky130_fd_sc_hd__a22o_1 _473_ (
    .A1(_083_),
    .A2(_119_),
    .B1(_137_),
    .B2(_082_),
    .X(_022_)
  );
  sky130_fd_sc_hd__a22o_1 _474_ (
    .A1(_084_),
    .A2(_119_),
    .B1(_137_),
    .B2(_083_),
    .X(_023_)
  );
  sky130_fd_sc_hd__a22o_1 _475_ (
    .A1(_085_),
    .A2(_119_),
    .B1(_137_),
    .B2(_084_),
    .X(_024_)
  );
  sky130_fd_sc_hd__a22o_1 _476_ (
    .A1(_086_),
    .A2(_119_),
    .B1(_137_),
    .B2(_085_),
    .X(_025_)
  );
  sky130_fd_sc_hd__nor2_1 _477_ (
    .A(_086_),
    .B(_117_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nor2_1 _478_ (
    .A(_119_),
    .B(_138_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nor3_1 _479_ (
    .A(_087_),
    .B(_166_),
    .C(_165_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__a21oi_1 _480_ (
    .A1(_167_),
    .A2(_166_),
    .B1(_165_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__o21bai_1 _481_ (
    .A1(_087_),
    .A2(_095_),
    .B1_N(_125_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__nand2_1 _482_ (
    .A(_167_),
    .B(_166_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__a21oi_1 _483_ (
    .A1(_167_),
    .A2(_166_),
    .B1(_097_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__a2111oi_0 _484_ (
    .A1(_098_),
    .A2(_129_),
    .B1(_136_),
    .C1(_139_),
    .D1(_120_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__o21ai_0 _485_ (
    .A1(_090_),
    .A2(_141_),
    .B1(_142_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__a211oi_1 _486_ (
    .A1(_091_),
    .A2(_125_),
    .B1(_120_),
    .C1(_117_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__nand2_1 _487_ (
    .A(_140_),
    .B(_143_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nand2_1 _488_ (
    .A(_079_),
    .B(_119_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nand4_1 _489_ (
    .A(_096_),
    .B(_126_),
    .C(_140_),
    .D(_144_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nand2_1 _490_ (
    .A(_048_),
    .B(_117_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__o21ai_0 _491_ (
    .A1(_100_),
    .A2(_118_),
    .B1(_057_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__nand2_1 _492_ (
    .A(_145_),
    .B(_146_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__and2_0 _493_ (
    .A(_060_),
    .B(_119_),
    .X(_147_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _494_ (
    .A(_079_),
    .SLEEP(_156_),
    .X(_069_)
  );
  sky130_fd_sc_hd__clkinv_1 _495_ (
    .A(_069_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__a21oi_1 _496_ (
    .A1(_079_),
    .A2(_147_),
    .B1(_156_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__nor2_1 _497_ (
    .A(_117_),
    .B(_148_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _498_ (
    .A(_080_),
    .SLEEP(_157_),
    .X(_070_)
  );
  sky130_fd_sc_hd__clkinv_1 _499_ (
    .A(_070_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__a21oi_1 _500_ (
    .A1(_080_),
    .A2(_147_),
    .B1(_157_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__nor2_1 _501_ (
    .A(_117_),
    .B(_149_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _502_ (
    .A(_081_),
    .SLEEP(_158_),
    .X(_071_)
  );
  sky130_fd_sc_hd__clkinv_1 _503_ (
    .A(_071_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__a21oi_1 _504_ (
    .A1(_081_),
    .A2(_147_),
    .B1(_158_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__nor2_1 _505_ (
    .A(_117_),
    .B(_150_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _506_ (
    .A(_082_),
    .SLEEP(_159_),
    .X(_072_)
  );
  sky130_fd_sc_hd__clkinv_1 _507_ (
    .A(_072_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__a21oi_1 _508_ (
    .A1(_082_),
    .A2(_147_),
    .B1(_159_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__nor2_1 _509_ (
    .A(_117_),
    .B(_151_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _510_ (
    .A(_083_),
    .SLEEP(_160_),
    .X(_073_)
  );
  sky130_fd_sc_hd__clkinv_1 _511_ (
    .A(_073_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__a21oi_1 _512_ (
    .A1(_083_),
    .A2(_147_),
    .B1(_160_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__nor2_1 _513_ (
    .A(_117_),
    .B(_152_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__a21oi_1 _514_ (
    .A1(_084_),
    .A2(_147_),
    .B1(_161_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__nor2_1 _515_ (
    .A(_117_),
    .B(_153_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__a21oi_1 _516_ (
    .A1(_085_),
    .A2(_147_),
    .B1(_162_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__nor2_1 _517_ (
    .A(_117_),
    .B(_154_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__a21oi_1 _518_ (
    .A1(_086_),
    .A2(_147_),
    .B1(_163_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__nor2_1 _519_ (
    .A(_117_),
    .B(_155_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _520_ (
    .A(_078_),
    .SLEEP(_058_),
    .X(_059_)
  );
  sky130_fd_sc_hd__dfrtp_1 _521_ (
    .CLK(clk),
    .D(_005_[0]),
    .Q(result[0]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _522_ (
    .CLK(clk),
    .D(_005_[1]),
    .Q(result[1]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _523_ (
    .CLK(clk),
    .D(_005_[2]),
    .Q(result[2]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _524_ (
    .CLK(clk),
    .D(_005_[3]),
    .Q(result[3]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _525_ (
    .CLK(clk),
    .D(_005_[4]),
    .Q(result[4]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _526_ (
    .CLK(clk),
    .D(_005_[5]),
    .Q(result[5]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _527_ (
    .CLK(clk),
    .D(_005_[6]),
    .Q(result[6]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _528_ (
    .CLK(clk),
    .D(_005_[7]),
    .Q(result[7]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _529_ (
    .CLK(clk),
    .D(_002_),
    .Q(calibrate),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _530_ (
    .CLK(clk),
    .D(_006_[0]),
    .Q(state[0]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _531_ (
    .CLK(clk),
    .D(_006_[1]),
    .Q(state[1]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _532_ (
    .CLK(clk),
    .D(_006_[2]),
    .Q(state[2]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _533_ (
    .CLK(clk),
    .D(_004_[0]),
    .Q(mask[0]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _534_ (
    .CLK(clk),
    .D(_004_[1]),
    .Q(mask[1]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _535_ (
    .CLK(clk),
    .D(_004_[2]),
    .Q(mask[2]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _536_ (
    .CLK(clk),
    .D(_004_[3]),
    .Q(mask[3]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _537_ (
    .CLK(clk),
    .D(_004_[4]),
    .Q(mask[4]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _538_ (
    .CLK(clk),
    .D(_004_[5]),
    .Q(mask[5]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _539_ (
    .CLK(clk),
    .D(_004_[6]),
    .Q(mask[6]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _540_ (
    .CLK(clk),
    .D(_004_[7]),
    .Q(mask[7]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _541_ (
    .CLK(clk),
    .D(_007_[0]),
    .Q(trim_mask[0]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _542_ (
    .CLK(clk),
    .D(_007_[1]),
    .Q(trim_mask[1]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _543_ (
    .CLK(clk),
    .D(_007_[2]),
    .Q(trim_mask[2]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _544_ (
    .CLK(clk),
    .D(_007_[3]),
    .Q(trim_mask[3]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _545_ (
    .CLK(clk),
    .D(_007_[4]),
    .Q(trim_mask[4]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _546_ (
    .CLK(clk),
    .D(_008_[0]),
    .Q(trim_val[0]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _547_ (
    .CLK(clk),
    .D(_008_[1]),
    .Q(trim_val[1]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _548_ (
    .CLK(clk),
    .D(_008_[2]),
    .Q(trim_val[2]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _549_ (
    .CLK(clk),
    .D(_008_[3]),
    .Q(trim_val[3]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _550_ (
    .CLK(clk),
    .D(_008_[4]),
    .Q(trim_val[4]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _551_ (
    .CLK(clk),
    .D(_003_),
    .Q(en_co_clk),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfstp_2 _552_ (
    .CLK(clk),
    .D(_000_[0]),
    .Q(cal_count[0]),
    .SET_B(rstn)
  );
  sky130_fd_sc_hd__dfstp_2 _553_ (
    .CLK(clk),
    .D(_000_[1]),
    .Q(cal_count[1]),
    .SET_B(rstn)
  );
  sky130_fd_sc_hd__dfstp_2 _554_ (
    .CLK(clk),
    .D(_000_[2]),
    .Q(cal_count[2]),
    .SET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _555_ (
    .CLK(clk),
    .D(_000_[3]),
    .Q(cal_count[3]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _556_ (
    .CLK(clk),
    .D(_001_[0]),
    .Q(cal_itt[0]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _557_ (
    .CLK(clk),
    .D(_001_[1]),
    .Q(cal_itt[1]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _558_ (
    .CLK(clk),
    .D(_001_[2]),
    .Q(cal_itt[2]),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _559_ (
    .CLK(clk),
    .D(_001_[3]),
    .Q(cal_itt[3]),
    .RESET_B(rstn)
  );
  assign co_clk = 1'h0;
  assign _161_ = result[5];
  assign _084_ = mask[5];
  assign ctln[5] = _066_;
  assign ctlp[5] = _074_;
  assign _162_ = result[6];
  assign _085_ = mask[6];
  assign ctln[6] = _067_;
  assign ctlp[6] = _075_;
  assign _163_ = result[7];
  assign _086_ = mask[7];
  assign ctln[7] = _068_;
  assign ctlp[7] = _076_;
  assign _167_ = state[2];
  assign _173_ = trim_mask[0];
  assign _053_ = cal_itt[0];
  assign _054_ = cal_itt[1];
  assign _056_ = cal_itt[3];
  assign _055_ = cal_itt[2];
  assign _077_ = en;
  assign _001_[0] = _013_;
  assign _001_[1] = _014_;
  assign _001_[2] = _015_;
  assign _001_[3] = _016_;
  assign _049_ = cal_count[0];
  assign _060_ = comp;
  assign _000_[0] = _009_;
  assign _050_ = cal_count[1];
  assign _000_[1] = _010_;
  assign _051_ = cal_count[2];
  assign _000_[2] = _011_;
  assign _052_ = cal_count[3];
  assign _000_[3] = _012_;
  assign _166_ = state[1];
  assign _165_ = state[0];
  assign _078_ = en_co_clk;
  assign _079_ = mask[0];
  assign _003_ = _018_;
  assign _178_ = trim_val[0];
  assign trimb[0] = _183_;
  assign _057_ = calibrate;
  assign _008_[0] = _043_;
  assign _179_ = trim_val[1];
  assign trimb[1] = _184_;
  assign _008_[1] = _044_;
  assign _180_ = trim_val[2];
  assign trimb[2] = _185_;
  assign _008_[2] = _045_;
  assign _181_ = trim_val[3];
  assign trimb[3] = _186_;
  assign _008_[3] = _046_;
  assign _182_ = trim_val[4];
  assign trimb[4] = _187_;
  assign _008_[4] = _047_;
  assign _174_ = trim_mask[1];
  assign _007_[0] = _038_;
  assign _175_ = trim_mask[2];
  assign _007_[1] = _039_;
  assign _176_ = trim_mask[3];
  assign _007_[2] = _040_;
  assign _177_ = trim_mask[4];
  assign _007_[3] = _041_;
  assign _007_[4] = _042_;
  assign _080_ = mask[1];
  assign _004_[0] = _019_;
  assign _081_ = mask[2];
  assign _004_[1] = _020_;
  assign _082_ = mask[3];
  assign _004_[2] = _021_;
  assign _083_ = mask[4];
  assign _004_[3] = _022_;
  assign _004_[4] = _023_;
  assign _004_[5] = _024_;
  assign _004_[6] = _025_;
  assign _004_[7] = _026_;
  assign valid = _188_;
  assign _006_[0] = _035_;
  assign _006_[1] = _036_;
  assign _006_[2] = _037_;
  assign _048_ = cal;
  assign _002_ = _017_;
  assign _156_ = result[0];
  assign _005_[0] = _027_;
  assign _157_ = result[1];
  assign _005_[1] = _028_;
  assign _158_ = result[2];
  assign _005_[2] = _029_;
  assign _159_ = result[3];
  assign _005_[3] = _030_;
  assign _160_ = result[4];
  assign _005_[4] = _031_;
  assign _005_[5] = _032_;
  assign _005_[6] = _033_;
  assign _005_[7] = _034_;
  assign _058_ = clk;
  assign clkc = _059_;
  assign sample = _164_;
  assign trim[0] = _168_;
  assign trim[1] = _169_;
  assign trim[2] = _170_;
  assign trim[3] = _171_;
  assign trim[4] = _172_;
  assign ctln[0] = _061_;
  assign ctlp[0] = _069_;
  assign ctln[1] = _062_;
  assign ctlp[1] = _070_;
  assign ctln[2] = _063_;
  assign ctlp[2] = _071_;
  assign ctln[3] = _064_;
  assign ctlp[3] = _072_;
  assign ctln[4] = _065_;
  assign ctlp[4] = _073_;
endmodule
