/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module sar_logic(clk, rstn, en, comp, cal, valid, \result[0] , \result[1] , \result[2] , \result[3] , \result[4] , \result[5] , \result[6] , \result[7] , sample, \ctlp[0] , \ctlp[1] , \ctlp[2] , \ctlp[3] , \ctlp[4] , \ctlp[5] , \ctlp[6] , \ctlp[7] , \ctln[0] , \ctln[1] , \ctln[2] , \ctln[3] , \ctln[4] , \ctln[5] , \ctln[6] , \ctln[7] , \trim[0] , \trim[1] , \trim[2] , \trim[3] , \trim[4] , \trimb[0] , \trimb[1] , \trimb[2] , \trimb[3] , \trimb[4] , clkc);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  input cal;
  wire \cal_count[0] ;
  wire \cal_count[1] ;
  wire \cal_count[2] ;
  wire \cal_count[3] ;
  wire \cal_itt[0] ;
  wire \cal_itt[1] ;
  wire \cal_itt[2] ;
  wire \cal_itt[3] ;
  wire calibrate;
  input clk;
  output clkc;
  input comp;
  output \ctln[0] ;
  output \ctln[1] ;
  output \ctln[2] ;
  output \ctln[3] ;
  output \ctln[4] ;
  output \ctln[5] ;
  output \ctln[6] ;
  output \ctln[7] ;
  output \ctlp[0] ;
  output \ctlp[1] ;
  output \ctlp[2] ;
  output \ctlp[3] ;
  output \ctlp[4] ;
  output \ctlp[5] ;
  output \ctlp[6] ;
  output \ctlp[7] ;
  input en;
  wire en_co_clk;
  wire \mask[0] ;
  wire \mask[1] ;
  wire \mask[2] ;
  wire \mask[3] ;
  wire \mask[4] ;
  wire \mask[5] ;
  wire \mask[6] ;
  wire \mask[7] ;
  output \result[0] ;
  output \result[1] ;
  output \result[2] ;
  output \result[3] ;
  output \result[4] ;
  output \result[5] ;
  output \result[6] ;
  output \result[7] ;
  input rstn;
  output sample;
  wire \state[0] ;
  wire \state[1] ;
  wire \state[2] ;
  output \trim[0] ;
  output \trim[1] ;
  output \trim[2] ;
  output \trim[3] ;
  output \trim[4] ;
  wire \trim_mask[0] ;
  wire \trim_mask[1] ;
  wire \trim_mask[2] ;
  wire \trim_mask[3] ;
  wire \trim_mask[4] ;
  wire \trim_val[0] ;
  wire \trim_val[1] ;
  wire \trim_val[2] ;
  wire \trim_val[3] ;
  wire \trim_val[4] ;
  output \trimb[0] ;
  output \trimb[1] ;
  output \trimb[2] ;
  output \trimb[3] ;
  output \trimb[4] ;
  output valid;
  sky130_fd_sc_hd__clkinv_1 _107_ (
    .A(\state[2] ),
    .Y(_039_)
  );
  sky130_fd_sc_hd__clkinv_1 _108_ (
    .A(\cal_count[1] ),
    .Y(_040_)
  );
  sky130_fd_sc_hd__clkinv_1 _109_ (
    .A(\cal_count[2] ),
    .Y(_041_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _110_ (
    .A(\mask[4] ),
    .SLEEP(\result[4] ),
    .X(\ctlp[4] )
  );
  sky130_fd_sc_hd__clkinv_1 _111_ (
    .A(\ctlp[4] ),
    .Y(\ctln[4] )
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _112_ (
    .A(\result[5] ),
    .SLEEP(\mask[5] ),
    .X(\ctlp[5] )
  );
  sky130_fd_sc_hd__clkinv_1 _113_ (
    .A(\ctlp[5] ),
    .Y(\ctln[5] )
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _114_ (
    .A(\result[6] ),
    .SLEEP(\mask[6] ),
    .X(\ctlp[6] )
  );
  sky130_fd_sc_hd__clkinv_1 _115_ (
    .A(\ctlp[6] ),
    .Y(\ctln[6] )
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _116_ (
    .A(\result[7] ),
    .SLEEP(\mask[7] ),
    .X(\ctlp[7] )
  );
  sky130_fd_sc_hd__clkinv_1 _117_ (
    .A(\ctlp[7] ),
    .Y(\ctln[7] )
  );
  sky130_fd_sc_hd__and4b_1 _118_ (
    .A_N(\cal_itt[3] ),
    .B(\cal_itt[2] ),
    .C(\cal_itt[0] ),
    .D(\cal_itt[1] ),
    .X(_042_)
  );
  sky130_fd_sc_hd__nand4b_1 _119_ (
    .A_N(\cal_itt[3] ),
    .B(\cal_itt[2] ),
    .C(\cal_itt[0] ),
    .D(\cal_itt[1] ),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nand2_1 _120_ (
    .A(\cal_itt[0] ),
    .B(_043_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nand2b_1 _121_ (
    .A_N(\state[1] ),
    .B(\state[0] ),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nand3b_1 _122_ (
    .A_N(\state[1] ),
    .B(\state[0] ),
    .C(\state[2] ),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nor2_1 _123_ (
    .A(_042_),
    .B(_046_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nand2_1 _124_ (
    .A(\trim_mask[0] ),
    .B(\cal_itt[0] ),
    .Y(_048_)
  );
  sky130_fd_sc_hd__a21oi_1 _125_ (
    .A1(_042_),
    .A2(_048_),
    .B1(_046_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__o21bai_1 _126_ (
    .A1(\state[2] ),
    .A2(en),
    .B1_N(_045_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__a22o_1 _127_ (
    .A1(_044_),
    .A2(_049_),
    .B1(_050_),
    .B2(\cal_itt[0] ),
    .X(_004_)
  );
  sky130_fd_sc_hd__xor2_1 _128_ (
    .A(\cal_itt[0] ),
    .B(\cal_itt[1] ),
    .X(_051_)
  );
  sky130_fd_sc_hd__o21ai_0 _129_ (
    .A1(_042_),
    .A2(_051_),
    .B1(_049_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nand2_1 _130_ (
    .A(\cal_itt[1] ),
    .B(_050_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand2_1 _131_ (
    .A(_052_),
    .B(_053_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__a21o_1 _132_ (
    .A1(\cal_itt[0] ),
    .A2(\cal_itt[1] ),
    .B1(\cal_itt[2] ),
    .X(_054_)
  );
  sky130_fd_sc_hd__nand4_1 _133_ (
    .A(\cal_itt[0] ),
    .B(\cal_itt[1] ),
    .C(\cal_itt[3] ),
    .D(\cal_itt[2] ),
    .Y(_055_)
  );
  sky130_fd_sc_hd__a32o_1 _134_ (
    .A1(_049_),
    .A2(_054_),
    .A3(_055_),
    .B1(_050_),
    .B2(\cal_itt[2] ),
    .X(_006_)
  );
  sky130_fd_sc_hd__a31oi_1 _135_ (
    .A1(\cal_itt[0] ),
    .A2(\cal_itt[1] ),
    .A3(\cal_itt[2] ),
    .B1(_039_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__o21a_1 _136_ (
    .A1(_050_),
    .A2(_056_),
    .B1(\cal_itt[3] ),
    .X(_007_)
  );
  sky130_fd_sc_hd__mux2i_1 _137_ (
    .A0(_050_),
    .A1(_047_),
    .S(\cal_count[0] ),
    .Y(_000_)
  );
  sky130_fd_sc_hd__xor2_1 _138_ (
    .A(\cal_count[0] ),
    .B(\cal_count[1] ),
    .X(_057_)
  );
  sky130_fd_sc_hd__xnor2_1 _139_ (
    .A(comp),
    .B(_057_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__a22oi_1 _140_ (
    .A1(_040_),
    .A2(_050_),
    .B1(_058_),
    .B2(_047_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nor3b_1 _141_ (
    .A(\cal_count[0] ),
    .B(\cal_count[1] ),
    .C_N(comp),
    .Y(_059_)
  );
  sky130_fd_sc_hd__and3b_1 _142_ (
    .A_N(comp),
    .B(\cal_count[1] ),
    .C(\cal_count[0] ),
    .X(_060_)
  );
  sky130_fd_sc_hd__nor2_1 _143_ (
    .A(_059_),
    .B(_060_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__xnor2_1 _144_ (
    .A(_041_),
    .B(_061_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__a22oi_1 _145_ (
    .A1(_041_),
    .A2(_050_),
    .B1(_062_),
    .B2(_047_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__mux2i_1 _146_ (
    .A0(_059_),
    .A1(_060_),
    .S(\cal_count[2] ),
    .Y(_063_)
  );
  sky130_fd_sc_hd__xnor2_1 _147_ (
    .A(\cal_count[3] ),
    .B(_063_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__a22o_1 _148_ (
    .A1(\cal_count[3] ),
    .A2(_050_),
    .B1(_064_),
    .B2(_047_),
    .X(_003_)
  );
  sky130_fd_sc_hd__nand2b_1 _149_ (
    .A_N(\state[2] ),
    .B(\state[0] ),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nor3b_1 _150_ (
    .A(\state[1] ),
    .B(_065_),
    .C_N(en),
    .Y(_066_)
  );
  sky130_fd_sc_hd__a21oi_1 _151_ (
    .A1(\trim_mask[0] ),
    .A2(_042_),
    .B1(_046_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__and3b_1 _152_ (
    .A_N(\state[2] ),
    .B(\state[1] ),
    .C(\state[0] ),
    .X(_068_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _153_ (
    .A(_068_),
    .SLEEP(\mask[0] ),
    .X(_069_)
  );
  sky130_fd_sc_hd__a21oi_1 _154_ (
    .A1(\state[1] ),
    .A2(\mask[0] ),
    .B1(_065_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__o22ai_1 _155_ (
    .A1(en_co_clk),
    .A2(_066_),
    .B1(_067_),
    .B2(_070_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nand3_1 _156_ (
    .A(en_co_clk),
    .B(_046_),
    .C(_065_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nand2_1 _157_ (
    .A(_071_),
    .B(_072_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _158_ (
    .A(\trim_mask[0] ),
    .SLEEP(\trim_val[0] ),
    .X(\trim[0] )
  );
  sky130_fd_sc_hd__clkinv_1 _159_ (
    .A(\trim[0] ),
    .Y(\trimb[0] )
  );
  sky130_fd_sc_hd__or3_1 _160_ (
    .A(\state[2] ),
    .B(\state[1] ),
    .C(\state[0] ),
    .X(_073_)
  );
  sky130_fd_sc_hd__nor3b_1 _161_ (
    .A(\state[2] ),
    .B(\state[0] ),
    .C_N(\state[1] ),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nand2_1 _162_ (
    .A(calibrate),
    .B(_074_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nand2_1 _163_ (
    .A(_073_),
    .B(_075_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__and3_1 _164_ (
    .A(\trim_val[0] ),
    .B(_073_),
    .C(_075_),
    .X(_077_)
  );
  sky130_fd_sc_hd__nor2_1 _165_ (
    .A(_043_),
    .B(_046_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__a31o_1 _166_ (
    .A1(\trim_mask[0] ),
    .A2(\cal_count[3] ),
    .A3(_078_),
    .B1(_077_),
    .X(_034_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _167_ (
    .A(\trim_val[1] ),
    .SLEEP(\trim_mask[1] ),
    .X(\trim[1] )
  );
  sky130_fd_sc_hd__clkinv_1 _168_ (
    .A(\trim[1] ),
    .Y(\trimb[1] )
  );
  sky130_fd_sc_hd__a31oi_1 _169_ (
    .A1(\cal_count[3] ),
    .A2(\trim_mask[1] ),
    .A3(_078_),
    .B1(\trim_val[1] ),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nor2_1 _170_ (
    .A(_076_),
    .B(_079_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _171_ (
    .A(\trim_val[2] ),
    .SLEEP(\trim_mask[2] ),
    .X(\trim[2] )
  );
  sky130_fd_sc_hd__clkinv_1 _172_ (
    .A(\trim[2] ),
    .Y(\trimb[2] )
  );
  sky130_fd_sc_hd__a21oi_1 _173_ (
    .A1(\cal_count[3] ),
    .A2(_078_),
    .B1(\trim_val[2] ),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nor3_1 _174_ (
    .A(_076_),
    .B(\trimb[2] ),
    .C(_080_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _175_ (
    .A(\trim_val[3] ),
    .SLEEP(\trim_mask[3] ),
    .X(\trim[3] )
  );
  sky130_fd_sc_hd__clkinv_1 _176_ (
    .A(\trim[3] ),
    .Y(\trimb[3] )
  );
  sky130_fd_sc_hd__a31oi_1 _177_ (
    .A1(\cal_count[3] ),
    .A2(\trim_mask[3] ),
    .A3(_078_),
    .B1(\trim_val[3] ),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nor2_1 _178_ (
    .A(_076_),
    .B(_081_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nor2_1 _179_ (
    .A(\trim_val[4] ),
    .B(\trim_mask[4] ),
    .Y(\trimb[4] )
  );
  sky130_fd_sc_hd__clkinv_1 _180_ (
    .A(\trimb[4] ),
    .Y(\trim[4] )
  );
  sky130_fd_sc_hd__a21oi_1 _181_ (
    .A1(\cal_count[3] ),
    .A2(_078_),
    .B1(\trim_val[4] ),
    .Y(_082_)
  );
  sky130_fd_sc_hd__o31ai_1 _182_ (
    .A1(_076_),
    .A2(\trimb[4] ),
    .A3(_082_),
    .B1(_073_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__a21oi_1 _183_ (
    .A1(calibrate),
    .A2(_074_),
    .B1(_078_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__a22o_1 _184_ (
    .A1(\trim_mask[1] ),
    .A2(_078_),
    .B1(_083_),
    .B2(\trim_mask[0] ),
    .X(_029_)
  );
  sky130_fd_sc_hd__a22o_1 _185_ (
    .A1(\trim_mask[2] ),
    .A2(_078_),
    .B1(_083_),
    .B2(\trim_mask[1] ),
    .X(_030_)
  );
  sky130_fd_sc_hd__a22o_1 _186_ (
    .A1(\trim_mask[3] ),
    .A2(_078_),
    .B1(_083_),
    .B2(\trim_mask[2] ),
    .X(_031_)
  );
  sky130_fd_sc_hd__a22o_1 _187_ (
    .A1(\trim_mask[4] ),
    .A2(_078_),
    .B1(_083_),
    .B2(\trim_mask[3] ),
    .X(_032_)
  );
  sky130_fd_sc_hd__o21ai_0 _188_ (
    .A1(_043_),
    .A2(_046_),
    .B1(\trim_mask[4] ),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nand2_1 _189_ (
    .A(_075_),
    .B(_084_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nor3_1 _190_ (
    .A(en),
    .B(\state[1] ),
    .C(_065_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _191_ (
    .A(_065_),
    .SLEEP(_085_),
    .X(_086_)
  );
  sky130_fd_sc_hd__a22o_1 _192_ (
    .A1(\mask[1] ),
    .A2(_068_),
    .B1(_086_),
    .B2(\mask[0] ),
    .X(_010_)
  );
  sky130_fd_sc_hd__a22o_1 _193_ (
    .A1(\mask[2] ),
    .A2(_068_),
    .B1(_086_),
    .B2(\mask[1] ),
    .X(_011_)
  );
  sky130_fd_sc_hd__a22o_1 _194_ (
    .A1(\mask[3] ),
    .A2(_068_),
    .B1(_086_),
    .B2(\mask[2] ),
    .X(_012_)
  );
  sky130_fd_sc_hd__a22o_1 _195_ (
    .A1(\mask[4] ),
    .A2(_068_),
    .B1(_086_),
    .B2(\mask[3] ),
    .X(_013_)
  );
  sky130_fd_sc_hd__a22o_1 _196_ (
    .A1(\mask[5] ),
    .A2(_068_),
    .B1(_086_),
    .B2(\mask[4] ),
    .X(_014_)
  );
  sky130_fd_sc_hd__a22o_1 _197_ (
    .A1(\mask[6] ),
    .A2(_068_),
    .B1(_086_),
    .B2(\mask[5] ),
    .X(_015_)
  );
  sky130_fd_sc_hd__a22o_1 _198_ (
    .A1(\mask[7] ),
    .A2(_068_),
    .B1(_086_),
    .B2(\mask[6] ),
    .X(_016_)
  );
  sky130_fd_sc_hd__nor2_1 _199_ (
    .A(\mask[7] ),
    .B(_066_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__nor2_1 _200_ (
    .A(_068_),
    .B(_087_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nor3_1 _201_ (
    .A(_039_),
    .B(\state[1] ),
    .C(\state[0] ),
    .Y(valid)
  );
  sky130_fd_sc_hd__a21oi_1 _202_ (
    .A1(\state[2] ),
    .A2(\state[1] ),
    .B1(\state[0] ),
    .Y(_088_)
  );
  sky130_fd_sc_hd__o21bai_1 _203_ (
    .A1(_039_),
    .A2(_045_),
    .B1_N(_074_),
    .Y(sample)
  );
  sky130_fd_sc_hd__nand2_1 _204_ (
    .A(\state[2] ),
    .B(\state[1] ),
    .Y(_089_)
  );
  sky130_fd_sc_hd__clkinv_1 _205_ (
    .A(_089_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__o21ai_0 _206_ (
    .A1(_047_),
    .A2(_090_),
    .B1(\state[0] ),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nand2_1 _207_ (
    .A(_048_),
    .B(_078_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nor3_1 _208_ (
    .A(_069_),
    .B(_085_),
    .C(_088_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nand3_1 _209_ (
    .A(_091_),
    .B(_092_),
    .C(_093_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _210_ (
    .A(_074_),
    .SLEEP(calibrate),
    .X(_094_)
  );
  sky130_fd_sc_hd__or4_1 _211_ (
    .A(_066_),
    .B(_069_),
    .C(_090_),
    .D(_094_),
    .X(_027_)
  );
  sky130_fd_sc_hd__nand2_1 _212_ (
    .A(\mask[0] ),
    .B(_068_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nand4_1 _213_ (
    .A(_046_),
    .B(_075_),
    .C(_089_),
    .D(_095_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand2_1 _214_ (
    .A(cal),
    .B(_066_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__o21ai_0 _215_ (
    .A1(_050_),
    .A2(_067_),
    .B1(calibrate),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nand2_1 _216_ (
    .A(_096_),
    .B(_097_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__and2_0 _217_ (
    .A(comp),
    .B(_068_),
    .X(_098_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _218_ (
    .A(\mask[0] ),
    .SLEEP(\result[0] ),
    .X(\ctlp[0] )
  );
  sky130_fd_sc_hd__clkinv_1 _219_ (
    .A(\ctlp[0] ),
    .Y(\ctln[0] )
  );
  sky130_fd_sc_hd__a21oi_1 _220_ (
    .A1(\mask[0] ),
    .A2(_098_),
    .B1(\result[0] ),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nor2_1 _221_ (
    .A(_066_),
    .B(_099_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _222_ (
    .A(\mask[1] ),
    .SLEEP(\result[1] ),
    .X(\ctlp[1] )
  );
  sky130_fd_sc_hd__clkinv_1 _223_ (
    .A(\ctlp[1] ),
    .Y(\ctln[1] )
  );
  sky130_fd_sc_hd__a21oi_1 _224_ (
    .A1(\mask[1] ),
    .A2(_098_),
    .B1(\result[1] ),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nor2_1 _225_ (
    .A(_066_),
    .B(_100_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _226_ (
    .A(\mask[2] ),
    .SLEEP(\result[2] ),
    .X(\ctlp[2] )
  );
  sky130_fd_sc_hd__clkinv_1 _227_ (
    .A(\ctlp[2] ),
    .Y(\ctln[2] )
  );
  sky130_fd_sc_hd__a21oi_1 _228_ (
    .A1(\mask[2] ),
    .A2(_098_),
    .B1(\result[2] ),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nor2_1 _229_ (
    .A(_066_),
    .B(_101_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _230_ (
    .A(\mask[3] ),
    .SLEEP(\result[3] ),
    .X(\ctlp[3] )
  );
  sky130_fd_sc_hd__clkinv_1 _231_ (
    .A(\ctlp[3] ),
    .Y(\ctln[3] )
  );
  sky130_fd_sc_hd__a21oi_1 _232_ (
    .A1(\mask[3] ),
    .A2(_098_),
    .B1(\result[3] ),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nor2_1 _233_ (
    .A(_066_),
    .B(_102_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__a21oi_1 _234_ (
    .A1(\mask[4] ),
    .A2(_098_),
    .B1(\result[4] ),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nor2_1 _235_ (
    .A(_066_),
    .B(_103_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__a21oi_1 _236_ (
    .A1(\mask[5] ),
    .A2(_098_),
    .B1(\result[5] ),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nor2_1 _237_ (
    .A(_066_),
    .B(_104_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__a21oi_1 _238_ (
    .A1(\mask[6] ),
    .A2(_098_),
    .B1(\result[6] ),
    .Y(_105_)
  );
  sky130_fd_sc_hd__nor2_1 _239_ (
    .A(_066_),
    .B(_105_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__a21oi_1 _240_ (
    .A1(\mask[7] ),
    .A2(_098_),
    .B1(\result[7] ),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nor2_1 _241_ (
    .A(_066_),
    .B(_106_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _242_ (
    .A(en_co_clk),
    .SLEEP(clk),
    .X(clkc)
  );
  sky130_fd_sc_hd__dfrtp_1 _243_ (
    .CLK(clk),
    .D(_018_),
    .Q(\result[0] ),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _244_ (
    .CLK(clk),
    .D(_019_),
    .Q(\result[1] ),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _245_ (
    .CLK(clk),
    .D(_020_),
    .Q(\result[2] ),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _246_ (
    .CLK(clk),
    .D(_021_),
    .Q(\result[3] ),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _247_ (
    .CLK(clk),
    .D(_022_),
    .Q(\result[4] ),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _248_ (
    .CLK(clk),
    .D(_023_),
    .Q(\result[5] ),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _249_ (
    .CLK(clk),
    .D(_024_),
    .Q(\result[6] ),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _250_ (
    .CLK(clk),
    .D(_025_),
    .Q(\result[7] ),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _251_ (
    .CLK(clk),
    .D(_008_),
    .Q(calibrate),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _252_ (
    .CLK(clk),
    .D(_026_),
    .Q(\state[0] ),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _253_ (
    .CLK(clk),
    .D(_027_),
    .Q(\state[1] ),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _254_ (
    .CLK(clk),
    .D(_028_),
    .Q(\state[2] ),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _255_ (
    .CLK(clk),
    .D(_010_),
    .Q(\mask[0] ),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _256_ (
    .CLK(clk),
    .D(_011_),
    .Q(\mask[1] ),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _257_ (
    .CLK(clk),
    .D(_012_),
    .Q(\mask[2] ),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _258_ (
    .CLK(clk),
    .D(_013_),
    .Q(\mask[3] ),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _259_ (
    .CLK(clk),
    .D(_014_),
    .Q(\mask[4] ),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _260_ (
    .CLK(clk),
    .D(_015_),
    .Q(\mask[5] ),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _261_ (
    .CLK(clk),
    .D(_016_),
    .Q(\mask[6] ),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _262_ (
    .CLK(clk),
    .D(_017_),
    .Q(\mask[7] ),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _263_ (
    .CLK(clk),
    .D(_029_),
    .Q(\trim_mask[0] ),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _264_ (
    .CLK(clk),
    .D(_030_),
    .Q(\trim_mask[1] ),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _265_ (
    .CLK(clk),
    .D(_031_),
    .Q(\trim_mask[2] ),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _266_ (
    .CLK(clk),
    .D(_032_),
    .Q(\trim_mask[3] ),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _267_ (
    .CLK(clk),
    .D(_033_),
    .Q(\trim_mask[4] ),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _268_ (
    .CLK(clk),
    .D(_034_),
    .Q(\trim_val[0] ),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _269_ (
    .CLK(clk),
    .D(_035_),
    .Q(\trim_val[1] ),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _270_ (
    .CLK(clk),
    .D(_036_),
    .Q(\trim_val[2] ),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _271_ (
    .CLK(clk),
    .D(_037_),
    .Q(\trim_val[3] ),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _272_ (
    .CLK(clk),
    .D(_038_),
    .Q(\trim_val[4] ),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _273_ (
    .CLK(clk),
    .D(_009_),
    .Q(en_co_clk),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfstp_2 _274_ (
    .CLK(clk),
    .D(_000_),
    .Q(\cal_count[0] ),
    .SET_B(rstn)
  );
  sky130_fd_sc_hd__dfstp_2 _275_ (
    .CLK(clk),
    .D(_001_),
    .Q(\cal_count[1] ),
    .SET_B(rstn)
  );
  sky130_fd_sc_hd__dfstp_2 _276_ (
    .CLK(clk),
    .D(_002_),
    .Q(\cal_count[2] ),
    .SET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _277_ (
    .CLK(clk),
    .D(_003_),
    .Q(\cal_count[3] ),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _278_ (
    .CLK(clk),
    .D(_004_),
    .Q(\cal_itt[0] ),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _279_ (
    .CLK(clk),
    .D(_005_),
    .Q(\cal_itt[1] ),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _280_ (
    .CLK(clk),
    .D(_006_),
    .Q(\cal_itt[2] ),
    .RESET_B(rstn)
  );
  sky130_fd_sc_hd__dfrtp_1 _281_ (
    .CLK(clk),
    .D(_007_),
    .Q(\cal_itt[3] ),
    .RESET_B(rstn)
  );
endmodule
